management:
  endpoints:
    web:
      exposure:
        include: "*" 
spring:
    security:
        user:
            name: admin
            password: password
            roles: ADMIN
    application:
        name: template-core
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    jackson:
        serialization:
            write-dates-as-timestamps: true
    liquibase:
        default-schema: dbo
        enabled: false
        change-log: classpath:data/changelog-master.xml
    output:
        ansi:
            enabled: ALWAYS
  
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
          
    datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=GcliniqueHAN
      username: SA
      password: 123
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
      database-platform: org.hibernate.dialect.SQLServerDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
            dialect: org.hibernate.dialect.SQLServer2012Dialect
      
      
    mail:
        username: 
        password: 
        host: 
        port: 465
        properties:
            mail:
                smtp:
                    connectiontimeout: 3000
                    auth: false
                    starttls:
                        enable: true

    profiles:
        include: no-liquibase
    config:
        use-legacy-processing: true
lang:
    secondary: ar

server:
    servlet:
        contextPath: /template-core
    port: 9000
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024


hystrix:
    command.default.execution.isolation.strategy: THREAD

email:
    from: marwen.hadrich@csys.com.tn
    to: marwen.hadrich@csys.com.tn


